apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/linuxsuren/ks/ks:v0.0.36
          command: ["/ks", "option", "migrate", "--service", '{{ include "ks-devops.fullname" . }}-apiserver.{{ .Release.Namespace }}:9090', "--namespace", "{{ .Release.Namespace }}"]
      serviceAccountName:  {{ include "ks-devops.serviceAccountName" . }}
      restartPolicy: Never
  backoffLimit: 4
