# permissions for end users to edit steptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: steptemplate-editor-role
rules:
- apiGroups:
  - devops.kubesphere.io
  resources:
  - steptemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - steptemplates/status
  verbs:
  - get
